import { GoogleSpreadsheet } from "google-spreadsheet";
import { JWT } from "google-auth-library";
import { db } from "@/utils/firebase";
import {
  collection,
  where,
  doc,
  getDocs,
  query,
  getDoc,
} from "firebase/firestore";

import { formatDate } from "./formatDate";
import { financialReportSheetDesign } from "./financialReport";

// Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
export const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: process.env.GOOGLE_CLIENT_EMAIL,
  key: process.env.GOOGLE_PRIVATE_KEY.replace(/\\n/g, "\n"),
  scopes: ["https://www.googleapis.com/auth/spreadsheets"],
});

export const report1 = new GoogleSpreadsheet(
  process.env.GOOGLE_SHEET_ID_1,
  serviceAccountAuth
);

export const report2 = new GoogleSpreadsheet(
  process.env.GOOGLE_SHEET_ID_2,
  serviceAccountAuth
);

export const generateReport = async (reportId) => {
  try {
    const reportDoc = doc(db, "Report", reportId);
    const reportSnapshot = await getDoc(reportDoc);
    if (!reportSnapshot.exists()) {
      console.log("No report is found in the database");
      return;
    }
    const reportDb = reportSnapshot.data();

    const audits = [];

    const auditReportRef = collection(db, "AuditReport");
    let q = query(auditReportRef, where("report_id", "==", reportId));
    let querySnapshot = await getDocs(q);
    const auditReports = querySnapshot.docs.map((doc) => doc.data());

    let ctr = 1;
    let promises = auditReports.map(async (docu) => {
      const auditRef = doc(db, "Audit", docu.audit_id);
      querySnapshot = await getDoc(auditRef);
      const audit = querySnapshot.data();
      const date = audit.audit_timestamp.toDate();
      const auditArray = [
        `A${ctr++}`,
        formatDate(date),
        date.toLocaleTimeString(),
        audit.audit_total_expense,
        audit.audit_gross_income,
        audit.audit_net_profit,
      ];
      audits.push(auditArray);
    });

    await Promise.all(promises);

    const inventories = await inventorySummary(
      reportDb.report_start_date,
      reportDb.report_end_date
    );

    await financialReportSheetDesign(reportDb, audits, inventories);
  } catch (error) {
    console.log(error);
  }
};

const inventorySummary = async (startDate, endDate) => {
  try {
    const cycleCountRef = collection(db, "CycleCount");
    const q = query(
      cycleCountRef,
      where("cycle_count_timestamp", ">=", startDate),
      where("cycle_count_timestamp", "<=", endDate)
    );
    const cycleSnapshot = await getDocs(q);
    const cycleCounts = cycleSnapshot.docs.map((doc) => doc.data());

    const filteredCycleCounts = cycleCounts.reduce((acc, cycleCount) => {
      const inventoryId = cycleCount.inventory_id;
      if (!acc[inventoryId]) {
        acc[inventoryId] = cycleCount;
      } else {
        acc[inventoryId].cycle_count_profit += cycleCount.cycle_count_profit;
        acc[inventoryId].cycle_count_income += cycleCount.cycle_count_income;
      }
      return acc;
    }, {});
    const result = Object.values(filteredCycleCounts);

    const data = [];
    let ctr = 1;

    const promises = result.map(async (cycle) => {
      const inventoryDoc = doc(db, "Inventory", cycle.inventory_id);
      const inventorySnapshot = await getDoc(inventoryDoc);
      if (!inventorySnapshot.exists()) {
        console.log("Inventory not found for ID:", cycle.inventory_id);
        return;
      }

      const inventory = inventorySnapshot.data();
      const productRef = doc(db, "Product", inventory.product_id);
      const productSnapshot = await getDoc(productRef);
      if (!productSnapshot.exists()) {
        console.log("Product not found for ID:", inventory.product_id);
        return;
      }
      const product_name = productSnapshot.data().product_name;
      const date = inventory.inventory_timestamp.toDate();
      const expense = cycle.cycle_count_income - cycle.cycle_count_profit;
      const combine = [
        `I${ctr++}`,
        formatDate(date),
        date.toLocaleTimeString(),
        product_name,
        inventory.inventory_total_units,
        inventory.inventory_wholesale_price,
        inventory.inventory_retail_price,
        expense,
        cycle.cycle_count_income,
        cycle.cycle_count_profit,
      ];
      data.push(combine);
    });

    await Promise.all(promises);
    return data;
  } catch (error) {
    console.log(error);
  }
};
